Parameters:
  VPCId: 
    Type: String
    Default: vpc-007612d4c8a0eea58
  SubnetID:
    Type: String 
    Default: subnet-0ab8485c45a4ddcde
  KeyName: 
    Type: String
    Default: dhruv-key-pair-Ohio

Resources:
  dhruvSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH access
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

  EC2instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b4624933067d393a
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetID
          GroupSet:
            - !Ref dhruvSG
          AssociatePublicIpAddress: true 
